In [49]:
import pandas as pd
import numpy as np
import json
import instruments

In [2]:
import pandas as pd
import json
import instruments

file = pd.read_csv("/Users/osman/OneDrive/Documents/ml_download_2021-09-27.csv",index_col="record_id")
dataframe = pd.DataFrame(file)

with open('data.json','r') as infile:
    data = json.load(infile)

for instrument in data:
    if instrument == 'adexi':
        adexi = instruments.Adexi(dataframe.columns,dataframe,data,instrument)
        adexi.getSections()
        adexi.addNewDataColumns()
    if instrument == 'aq-10':
        print('this gets executed')
        aq10 = instruments.AQ10(dataframe.columns,dataframe,data,instrument)
        aq10.getSections()
        aq10.addNewDataColumns()

'''
Stores the completed document with the calculated scores
Path must be specified

Great documentation in https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html

path formats allowed: Example: C:\\Users\\user\\Documents\\instrumenrs_output.csv
                                C:/Users/user/Documents/instruments_output.csv
'''
dataframe.to_csv(path_or_buf="C:\\Users\\osman\\OneDrive\\Documents\\ml_download_2021-09-27_OUT.csv" , na_rep='NaN')

KeyError: 'adexi_scored-total_s1_r1_e1'

In [28]:
df

,adexi_s1_r1_e1_timestamp,adexi_i1_s1_r1_e1,adexi_i2_s1_r1_e1,adexi_i3_s1_r1_e1,adexi_i4_s1_r1_e1,adexi_i5_s1_r1_e1,adexi_i6_s1_r1_e1,adexi_i7_s1_r1_e1,adexi_i8_s1_r1_e1,adexi_i9_s1_r1_e1,...,adexi_i6_s1_r1_e2,adexi_i7_s1_r1_e2,adexi_i8_s1_r1_e2,adexi_i9_s1_r1_e2,adexi_i10_s1_r1_e2,adexi_i11_s1_r1_e2,adexi_i12_s1_r1_e2,adexi_i13_s1_r1_e2,adexi_i14_s1_r1_e2,adexi_s1_r1_e2_complete
participant,,,,,,,,,,,,,,,,,,,,,
1001445,NaN,1,2.0,3,5,2.0,4.0,4,5,4,...,4,4,5,4,2,3,2,2,3,NaN
1001446,NaN,2,5.0,2,4,5.0,3.0,4,4,4,...,3,4,4,4,4,3,5,5,5,NaN
1001447,NaN,3,NaN,5,3,NaN,4.0,4,4,5,...,4,4,4,5,1,1,3,6,3,NaN
1001448,NaN,1,2.0,4,2,4.0,1.0,2,3,4,...,1,2,3,4,5,4,3,2,3,NaN
1001449,NaN,5,2.0,5,3,2.0,2.0,1,1,2,...,2,1,1,2,3,1,5,1,1,NaN
1001450,NaN,5,5.0,3,5,3.0,NaN,1,1,4,...,2,1,1,4,1,2,3,1,3,NaN
1001451,NaN,4,4.0,2,4,3.0,5.0,4,4,4,...,5,4,4,4,4,4,4,4,4,NaN
1001452,NaN,3,5.0,4,3,3.0,3.0,2,2,2,...,3,2,2,2,2,2,1,1,1,NaN
1001453,NaN,2,5.0,3,2,4.0,4.0,3,4,4,...,4,3,4,4,4,4,4,4,5,NaN

In [30]:
df.index[df['adexi_i2_s1_r1_e1'] == 2.0].tolist()

[1001445, 1001448, 1001449]

In [41]:
df.columns.get_loc('adexi_i3_s1_r1_e1')

3

In [50]:
df.iloc[0,df.columns.get_loc('adexi_i3_s1_r1_e1')] = np.NAN

In [51]:
df.iloc[0,df.columns.get_loc('adexi_i3_s1_r1_e1')]

nan

In [18]:
with open('data.json','r') as infile:
    data = json.load(infile)

In [19]:
for instrument in data:
    if instrument == 'adexi':
        adexi = instruments.Adexi(dataframe.columns,dataframe,data)
        adexi.getSections()
        adexi.addNewDataColumns(instrument)

In [5]:
dataframe[dataframe.columns[11:22]]

,adexi_i11_s1_r1_e1,adexi_i12_s1_r1_e1,adexi_i13_s1_r1_e1,adexi_i14_s1_r1_e1,adexi_s1_r1_e1_complete,adexi_scored-inh_s1_r1_e1,adexi_scored-wm_s1_r1_e1,adexi_total-score_s1_r1_e1,adexi_s1_r1_e2_timestamp,adexi_i1_s1_r1_e2,adexi_i2_s1_r1_e2
participant,,,,,,,,,,,
1001445,3,2,2,3,NaN,17.0,25.0,42.0,NaN,1,2
1001446,3,5,5,5,NaN,18.0,37.0,55.0,NaN,2,5
1001447,1,3,6,3,NaN,NaN,NaN,NaN,NaN,3,3
1001448,4,3,2,3,NaN,15.0,25.0,40.0,NaN,1,2
1001449,1,5,1,1,NaN,14.0,20.0,34.0,NaN,5,2
1001450,2,3,1,3,NaN,NaN,NaN,NaN,NaN,5,5
1001451,4,4,4,4,NaN,19.0,35.0,54.0,NaN,4,4
1001452,2,1,1,1,NaN,13.0,21.0,34.0,NaN,3,5
1001453,4,4,4,5,NaN,18.0,34.0,52.0,NaN,2,5

In [6]:
dataframe[dataframe.columns[32:]]

,adexi_i13_s1_r1_e2,adexi_i14_s1_r1_e2,adexi_s1_r1_e2_complete,adexi_scored-inh_s1_r1_e2,adexi_scored-wm_s1_r1_e2,adexi_total-score_s1_r1_e2
participant,,,,,,
1001445,2,3,NaN,17,25,42
1001446,5,5,NaN,18,37,55
1001447,6,3,NaN,16,34,50
1001448,2,3,NaN,15,25,40
1001449,1,1,NaN,14,20,34
1001450,1,3,NaN,14,25,39
1001451,4,4,NaN,19,35,54
1001452,1,1,NaN,13,21,34
1001453,4,5,NaN,18,34,52

In [53]:
wm = True

In [56]:
inh = True

In [57]:
wm == inh

True